
name: Multi-Agent Orchestrator CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest tests/

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build orchestrator image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/orchestrator:latest -f Dockerfile.orchestrator .
      - name: Build agent image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/agent:latest -f Dockerfile.agent .

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository }}/orchestrator:latest
          docker push ghcr.io/${{ github.repository }}/agent:latest

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy with docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d --remove-orphans
